const userDetails = [
  {
    userId: 1,
    fullName: 'Student1',
    userName: 'Raj',
    dp: '',
    email: 'xyz@iitg.ac.in',
    phone: '1234567890',
    location: 'Lohit Hostel, IIT Guwahati',
    favItems: [
      {
        itemId: 1,
        itemName: 'Bread Omelette',
        // price: 30,
        itemImage: '',
        // itemRating: 4.5,
        // isBestSeller: true,
        isVeg: false,
        // isRecommended: true,
        // inStock: true,
      },
      {
        itemId: 2,
        itemName: 'Maggi',
        // price: 30,
        itemImage: '',
        // itemRating: 4.5,
        // isBestSeller: true,
        isVeg: true,
        // isRecommended: true,
        // inStock: true,
      },
    ],
    reviews: [
      {
        reviewId: 1,
        // reviewerName: 'Student1',
        comment: 'Good food',
        reviewRating: 4.5,
        // reviewerImage: '',
      },
      {
        reviewId: 2,
        // reviewerName: 'Student2',
        comment: 'Okayish food',
        reviewRating: 4,
        // reviewerImage: '',
      },
    ],
    favShops: [
      {
        shopId: 1,
        name: 'Lohit Canteen',
        image: '',
        rating: 4.5,
        description: 'Canteen in Lohit Hostel',
      },
    ],
    shopId: '',
  },
  {
    userId: 2,
    fullName: 'Student2',
    userName: 'Kuldeep',
    dp: '',
    email: 'abc@iitg.ac.in',
    phone: '9234567890',
    location: 'Disang Hostel, IIT Guwahati',
    favItems: [
      {
        itemId: 1,
        itemName: 'Bread Omelette',
        // price: 30,
        itemImage: '',
        // itemRating: 4.5,
        // isBestSeller: true,
        isVeg: false,
        // isRecommended: true,
        // inStock: true,
      },
      {
        itemId: 2,
        itemName: 'Paratha',
        // price: 30,
        itemImage: '',
        // itemRating: 4.5,
        // isBestSeller: true,
        isVeg: true,
        // isRecommended: true,
        // inStock: true,
      },
    ],
    reviews: [
      {
        reviewId: 1,
        // reviewerName: 'Student1',
        comment: 'Good food',
        reviewRating: 4.5,
        // reviewerImage: '',
      },
      {
        reviewId: 2,
        // reviewerName: 'Student2',
        comment: 'Okayish food',
        reviewRating: 4,
        // reviewerImage: '',
      },
    ],
    favShops: [
      {
        shopId: 2,
        name: 'Disang Canteen',
        image: '',
        rating: 4.5,
        description: 'Canteen in Disang Hostel',
      },
      {
        shopId: 1,
        name: 'Lohit Canteen',
        image: '',
        rating: 4.5,
        description: 'Canteen in Lohit Hostel',
      },
    ],
    shopId: '',
  },
  // Add more dummy users here
];

export default userDetails;
