version: '3'
services:

 rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - 5672:5672
 pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=KULDEEPRANJAN39@GMAIL.COM
      - PGADMIN_DEFAULT_PASSWORD=postgres\
    ports:
      - 5050:80    
 postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
#  server:
#   working_dir: /usr/src/app
#   build: 
#     context: . 
#     dockerfile: dockerfile.dev
#   container_name: server
#   restart: always
#   ports:
#    - 8080:8080
#   volumes:
#    - /usr/src/app/node_modules
#    - .:/usr/src/app